# coding: utf-8

"""
    Cloud Speech-to-Text API

    Converts audio to text by applying powerful neural network models. <br> **PLEASE NOTE**: This API is provided by Google, beside the documentation provide below, you can find Google API documentation [here](https://cloud.google.com/speech-to-text/docs/reference/rest). You can refer to the Google documentation as well except by the URLs needed to call the API and that are documented here below.  # noqa: E501

    OpenAPI spec version: v3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gcloudspeechtotext
from models.speech_context import SpeechContext  # noqa: E501
from gcloudspeechtotext.rest import ApiException


class TestSpeechContext(unittest.TestCase):
    """SpeechContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpeechContext(self):
        """Test SpeechContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gcloudspeechtotext.models.speech_context.SpeechContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
