# coding: utf-8

"""
    Cloud Speech-to-Text API

    Converts audio to text by applying powerful neural network models. <br> **PLEASE NOTE**: This API is provided by Google, beside the documentation provide below, you can find Google API documentation [here](https://cloud.google.com/speech-to-text/docs/reference/rest). You can refer to the Google documentation as well except by the URLs needed to call the API and that are documented here below.  # noqa: E501

    OpenAPI spec version: v3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ListOperationsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'next_page_token': 'str',
        'operations': 'list[Operation]'
    }

    attribute_map = {
        'next_page_token': 'nextPageToken',
        'operations': 'operations'
    }

    def __init__(self, next_page_token=None, operations=None):  # noqa: E501
        """ListOperationsResponse - a model defined in Swagger"""  # noqa: E501
        self._next_page_token = None
        self._operations = None
        self.discriminator = None
        if next_page_token is not None:
            self.next_page_token = next_page_token
        if operations is not None:
            self.operations = operations

    @property
    def next_page_token(self):
        """Gets the next_page_token of this ListOperationsResponse.  # noqa: E501

        The standard List next-page token.  # noqa: E501

        :return: The next_page_token of this ListOperationsResponse.  # noqa: E501
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token):
        """Sets the next_page_token of this ListOperationsResponse.

        The standard List next-page token.  # noqa: E501

        :param next_page_token: The next_page_token of this ListOperationsResponse.  # noqa: E501
        :type: str
        """

        self._next_page_token = next_page_token

    @property
    def operations(self):
        """Gets the operations of this ListOperationsResponse.  # noqa: E501

        A list of operations that matches the specified filter in the request.  # noqa: E501

        :return: The operations of this ListOperationsResponse.  # noqa: E501
        :rtype: list[Operation]
        """
        return self._operations

    @operations.setter
    def operations(self, operations):
        """Sets the operations of this ListOperationsResponse.

        A list of operations that matches the specified filter in the request.  # noqa: E501

        :param operations: The operations of this ListOperationsResponse.  # noqa: E501
        :type: list[Operation]
        """

        self._operations = operations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListOperationsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListOperationsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
