# coding: utf-8

# flake8: noqa

"""
    Cloud Speech-to-Text API

    Converts audio to text by applying powerful neural network models. <br> **PLEASE NOTE**: This API is provided by Google, beside the documentation provide below, you can find Google API documentation [here](https://cloud.google.com/speech-to-text/docs/reference/rest). You can refer to the Google documentation as well except by the URLs needed to call the API and that are documented here below.  # noqa: E501

    OpenAPI spec version: v3.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from gcloudspeechtotext.api.operations_api import OperationsApi
from gcloudspeechtotext.api.speech_api import SpeechApi
# import ApiClient
from gcloudspeechtotext.api_client import ApiClient
from gcloudspeechtotext.configuration import Configuration
# import models into sdk package
from gcloudspeechtotext.models.list_operations_response import ListOperationsResponse
from gcloudspeechtotext.models.long_running_recognize_metadata import LongRunningRecognizeMetadata
from gcloudspeechtotext.models.long_running_recognize_request import LongRunningRecognizeRequest
from gcloudspeechtotext.models.long_running_recognize_response import LongRunningRecognizeResponse
from gcloudspeechtotext.models.operation import Operation
from gcloudspeechtotext.models.recognition_audio import RecognitionAudio
from gcloudspeechtotext.models.recognition_config import RecognitionConfig
from gcloudspeechtotext.models.recognition_metadata import RecognitionMetadata
from gcloudspeechtotext.models.recognize_request import RecognizeRequest
from gcloudspeechtotext.models.recognize_response import RecognizeResponse
from gcloudspeechtotext.models.speaker_diarization_config import SpeakerDiarizationConfig
from gcloudspeechtotext.models.speech_context import SpeechContext
from gcloudspeechtotext.models.speech_recognition_alternative import SpeechRecognitionAlternative
from gcloudspeechtotext.models.speech_recognition_result import SpeechRecognitionResult
from gcloudspeechtotext.models.status import Status
from gcloudspeechtotext.models.word_info import WordInfo
